### ISSUE TITLE
Regression with New Line IDs

### ISSUE THREAD

**Issue by taylorhadden** [typewriter-editor/typewriter-document#3]
About a year ago, we resolved an issue where inserting a new line would "steal" the id of the current line. I believe this was change 23c638f0f5f9 in the main typewriter-editor repository. This problem is now back (I'm not sure when it happened).

To summarize the issue, here is the essentials of what happens.

Given a starting line with an id:
```
(5k6740) This is my fancy line
```

If you then insert a newline within this line, the new line takes the ID of the existing line:
```
(2354k) This is my fancy
(5k6740) line
```

This causes issues with rendering stability. The existing line is detected as a new line and is completely regenerated. Any custom elements are reconstructed, and thus must pay their initialization cost.

**Comment by jacwright** [comment]
This has been fixed as well as when you delete a newline to keep the first ID. Ideally it would "know" whether the newline is being added at the beginning vs end of a paragraph and wether the deleted newline is at the beginning or end, but since the more common case is at the end of a paragraph, keeping the ID from the previous paragraph consistent is the better option.
